project:
  type: book

book:
  title: "teaching_material_book"
  author: "Jane Doe"
  date: "11/24/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

