project:
  type: book

book:
  title: "teaching_material_book"
  author: "Stefan Thoma"
  date: "`r format(Sys.time(), '%d %B, %Y')`"
  chapters:
    - index.qmd
    - introduction.qmd
    - data.qmd           
    - efficacy.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    css: styles.css
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

