name: Spellcheck
on:
  pull_request: {branches: ['master']}
jobs:
  Spelling:
    runs-on: ubuntu-latest
    container: {image: "rocker/tidyverse:4.2.1"}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install spelling
        run: if (!require("spelling")) install.packages("spelling")
        shell: Rscript {0}
      - name: Run Spelling Check test
        run: spelling::spell_check_files(list.files()[endsWith(list.files(), "md")], ignore = read.csv("inst/WORDLIST")[[1]])
        shell: Rscript {0}