name: Style
on:
  pull_request: {branches: ['master']}
jobs:
  Style:
    runs-on: ubuntu-latest
    container: {image: "rocker/tidyverse:4.2.1"}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install styler
        run: if (!require("styler")) remotes::install_github("r-lib/styler")
        shell: Rscript {0}
      - name: Run styler
        run: styler::style_dir(dry = "fail")
        shell: Rscript {0}
